import React from 'react';
import aboutlogo from '../images/aboutlogo.png';
import '../pages/CSS/AboutPage.css';

function AboutPage() {
    return (
        <div className="about-container">
            <img src={aboutlogo} alt="Company Logo" />
            <h1>About Us</h1>
            <p>HELPING HAND ALLOWS THOSE EXPERIENCING HOMELESSNESS TO RECEIVE FINANCIAL SUPPORT RELEVANT TO THEIR CURRENT NEEDS.</p>
            <p>WORKING WITH REGISTERED CHARITIES, HELPING HAND CREATES PROFILES BASED ON THE NEEDS OUTLINED BY OUR USERS. ONCE A DONATION HAS BEEN MADE, IT CAN BE COLLECTED BY THE RECEIVED AT THE CHARITY THEY HAVE REGISTERED THROUGH.</p>
            <p>HELPERS CAN MAKE ONE-TIME OR RECURRING DONATIONS. THESE CONTRIBUTIONS ARE TYPICALLY SMALL, AFFORDABLE AMOUNTS, MAKING IT EASY FOR ANYONE TO BECOME A HELPER.</p>
            <p>HELPING HAND PROVIDES A SAFE AND SECURE PLATFORM TO THOSE WHO NEED IT MOST WHILST ENSURING 100% OF THE FUNDS GET TO THE RIGHT PLACE.</p>
        </div>
    );
}

export default AboutPage;

